// <auto-generated />
using System;
using HouseHold.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseHold.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812135300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseHold.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IncomeClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncomeId");

                    b.HasIndex("IncomeClassId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("HouseHold.Models.IncomeClass", b =>
                {
                    b.Property<int>("IncomeClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeClassId"));

                    b.Property<string>("IncomeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncomeClassId");

                    b.ToTable("IncomeClasses");
                });

            modelBuilder.Entity("HouseHold.Models.IncomeType", b =>
                {
                    b.Property<int>("IncomeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomeTypeId"));

                    b.Property<int>("IncomeClassId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncomeTypeId");

                    b.HasIndex("IncomeClassId");

                    b.ToTable("IncomeTypes");
                });

            modelBuilder.Entity("HouseHold.Models.MonthlyBudget", b =>
                {
                    b.Property<int>("MonthlyBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlyBudgetId"));

                    b.Property<int>("BudgetAmount")
                        .HasColumnType("int");

                    b.Property<int>("MonthNum")
                        .HasColumnType("int");

                    b.Property<int>("YearNum")
                        .HasColumnType("int");

                    b.HasKey("MonthlyBudgetId");

                    b.ToTable("MonthlyBudgets");
                });

            modelBuilder.Entity("HouseHold.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectNameId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SubjectNameId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HouseHold.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("HouseHold.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("HouseHold.Models.SubjectName", b =>
                {
                    b.Property<int>("SubjectNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectNameId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectNameId");

                    b.ToTable("SubjectNames");
                });

            modelBuilder.Entity("HouseHold.Models.Income", b =>
                {
                    b.HasOne("HouseHold.Models.IncomeClass", "IncomeClassNavigation")
                        .WithMany()
                        .HasForeignKey("IncomeClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeClassNavigation");
                });

            modelBuilder.Entity("HouseHold.Models.IncomeType", b =>
                {
                    b.HasOne("HouseHold.Models.IncomeClass", null)
                        .WithMany("IncomeTypes")
                        .HasForeignKey("IncomeClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseHold.Models.Payment", b =>
                {
                    b.HasOne("HouseHold.Models.PaymentMethod", "PaymentMethodNavigation")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("HouseHold.Models.PaymentType", "PaymentTypeNavigation")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseHold.Models.SubjectName", "SubjectNameNavigation")
                        .WithMany()
                        .HasForeignKey("SubjectNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethodNavigation");

                    b.Navigation("PaymentTypeNavigation");

                    b.Navigation("SubjectNameNavigation");
                });

            modelBuilder.Entity("HouseHold.Models.PaymentMethod", b =>
                {
                    b.HasOne("HouseHold.Models.PaymentType", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseHold.Models.IncomeClass", b =>
                {
                    b.Navigation("IncomeTypes");
                });

            modelBuilder.Entity("HouseHold.Models.PaymentType", b =>
                {
                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
